### PR TITLE
Unable to download the Eclipselink libraries #4

### PR DESCRIPTION
**Pull request by lak-proddev**
Change-Id: I67020fc5f62d5f427a7706ac36959919ceb2567b

### CODE REVIEW

**Comment by lak-proddev** [comment]
@nitind  I am waiting for your review

**Comment by erik-brangs** [comment]
I thought the point of having this file on the website was to allow changes outside of releases.

The files on the website can be changed via the [website GitLab](https://gitlab.eclipse.org/eclipse/webtools/webtools-website).

**Review by nitind — COMMENTED** [review]
As Erik mentioned, the URL has changed due to site migration, but that's easily fixable.

On the other hand, updates to the eclipselink-downloadable-libs.xml contents to point to more recent releases would surely be appreciated.

**Comment by lak-proddev** [comment]
> On the other hand, updates to the eclipselink-downloadable-libs.xml contents to point to more recent releases would surely be appreciated.


Will add part of the JPA 3.0 support

**Pull request closed without merging**
